# Generated by Django 5.1.5 on 2025-02-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detection',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='detection',
            name='video_clip',
            field=models.FileField(blank=True, null=True, upload_to='detection_videos/'),
        ),
        migrations.AddField(
            model_name='detection',
            name='video_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='video_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='camera_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detection',
            name='confidence_score',
            field=models.FloatField(),
        ),
    ]
