# Generated by Django 5.1.5 on 2025-02-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0002_alter_detection_options_detection_video_clip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='url',
            field=models.URLField(blank=True, help_text='URL for IP camera (optional)', max_length=500, null=True),
        ),
    ]
